email: akshatjain1502@gmail.com
password: rdsharma123

disableAntiLock: True

remote: False

experienceLevel:

 internship: False
 entry: True
 associate: True
 mid-senior level: True
 director: False
 executive: False

jobTypes:
 full-time: True
 contract: True
 part-time: True
 temporary: False
 internship: False
 other: False
 volunteer: False

date:
 all time: True
 month: False
 week: False
 24 hours: False

positions:
  - Software Engineer
  - Software Developer
  # - Data Analyst
  - Python Developer
  # - Java Developer
  - Android Developer
  - Flutter Developer
  - Frontend Developer
  - Backend Developer
  - Full Stack Developer
  # - Computer Vision Engineer
  # - Machine Learning Engineer
  # - Graduate Software Developer
  # - Machine Learning Engineer
  - Data Engineering
  # - Data Science
  # - Computer Vision
 #- A third position
 #- ...
locations:
 - London, UK
 - United Kingdom
 - Eurpoe
#  - United States
 #- A second location
 #- A third location
 #- ...
distance: 100

outputFileDirectory: ~D:/Akshat/bot/

companyBlacklist:
 #- company
 #- company2

titleBlacklist:
 #- word1
 #- word2

posterBlacklist:
 #- name1
 #- name2

uploads:
 resume: D:\Akshat\Application\applicatipon\CV\Akshat_Jain_R_SD.pdf.pdf
 # Cover letter is optional
 #coverLetter: C:\Users\myDirectory\CoverLettter.pdf


# ------------ QA section -------------------

# ------------ Additional parameters: checkboxes ---------------
checkboxes:
 # Do you have a valid driver's license? (yes/no checkbox)
 driversLicence: True
 # Will you now, or in the future, require sponsorship for employment visa status (e.g. H-1B visa status)? (yes/no checkbox)
 # This is relative to the location and your citizenship applying above, and same with legallyAuthorized.
 requireVisa: False
 # Are you legally authorized to work in COUNTRY? (yes/no checkbox)
 legallyAuthorized: True
 # We must fill this position urgently. Can you start immediately? (yes/no checkbox)
 urgentFill: True
 # Are you comfortable commuting to this job's location? (yes/no checkbox)
 commute: True
 # Are you comfortable working in a remote environment? (yes/no checkbox)
 remote: True
 # Are you comfortable working in a remote environment? (yes/no checkbox)
 hybrid: True
 # Are you comfortable taking a drug in accordance with local/state laws? (yes/no checkbox)
 drugTest: True
 # Are you willing to complete an assessment? (yes/no checkbox)
 assessment: True
 # Have you completed the following level of education: DEGREE TYPE? (yes/no checkbox)
 degreeCompleted:
  - High School Diploma
  - Bachelor's Degree
  # - Associate's Degree
  - Master's Degree
  # - Master of Business Administration
  # - Doctor of Philosophy
  # - Doctor of Medicine
  # - Doctor of Law
 # Are you willing to undergo a background check, in accordance with local law/regulations?
 backgroundCheck: True
 # Are You based in UK or Europe?
 based: True
 sexualOrientation: heterosexual/Straight
 citizenship: False
# ------------ Additional parameters: universityGpa ---------------
universityGpa: 2:1

# ------------ Additional parameters: salaryMinimum ---------------
salaryMinimum: 35000

# ------------ Additional parameters: languages ---------------
languages:
 english: Native or bilingual # None, Conversational, Professional, Native or bilingual

# ------------ Additional parameters: years of experience ---------------
# How many years of work experience do you have ...? (whole numbers only)
experience:
 # normal ones
 Accounting/Auditing: 0
 Administrative : 0
 Advertising : 0
 Analyst : 0
 Art/Creative: 0
 Business Development: 0
 Consulting: 0
 Customer Service: 0
 Distribution Design: 0
 Education: 0
 Engineering: 1
 Finance: 0
 General Business: 0
 Health Care Provider: 0
 Human Resources: 0
 Information Technology: 0
 Legal: 0
 Management: 0
 Manufacturing: 0
 Marketing: 0
 Public Relations: 0
 Purchasing: 0
 Product Management: 0
 Project Management: 0
 Production: 0
 Quality Assurance: 0
 Research: 1
 Sales: 0
 Science: 0
 Strategy/Planning: 0
 Supply Chain: 0
 Training: 0
 Writing/Editing: 0
 python: 3
 Machine Learning: 2
 C++: 2
 Deep Learning: 1
 Start: 1
 selenium: 1
 AWS: 2
 java: 2
 # default to put for any industry/skill that you did not list
 default: 0

# ------------ Additional parameters: personal info ---------------
personalInfo:
 First Name: Akshat
 Last Name: Jain
 Phone Country Code: United Kingdom (+44) # See linkedin for your country code, must be exact according to the international platform, i.e. Italy (+39) not Italia (+39)
 Mobile Phone Number: 07867054538
 Street address: 57, 200 Norforlk Park
 City: Sheffield # Include the state/province as well!
 State: South YorkShire
 Zip: S2 2UA  
 Linkedin: https://www.linkedin.com/in/i-akshat-jain/
 Website: https://github.com/i-akshat-jain/ # github/website is interchangeable here

# ------------ Additional parameters: USA employment crap ---------------
eeo:
 gender: Male
 race: Asian Indian/Asian
 vetran: None
 disability: None
 citizenship: Indian
 clearance: yes